name: Auto Sync Excel Data

on:
  schedule:
    - cron: '0 * * * *'  # تشغيل كل ساعة
  workflow_dispatch:  # للتشغيل اليدوي

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Create data directory
        run: mkdir -p data  # يُنشئ المجلد إذا لم يكن موجودًا
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          pip install pandas openpyxl  # إزالة حزمة 'requests' غير الضرورية
          
      - name: Convert Excel to JSON
        run: |
          python - <<EOF
          import pandas as pd
          import json
          from datetime import datetime
          
          # قراءة ملف Excel مباشرةً من المجلد 'data/' في المستودع
          df = pd.read_excel('data/certificates.xlsx', keep_default_na=False)
          certificates = df.to_dict('records')
          
          # معالجة التواريخ
          for cert in certificates:
              date_fields = [
                  'Column1.employee_courses_degree.certificate_date',
                  'Column1.date_of_joining'
              ]
              for field in date_fields:
                  if field in cert and pd.notnull(cert[field]):
                      if isinstance(cert[field], datetime):
                          cert[field] = cert[field].strftime('%Y-%m-%d')
                      else:
                          cert[field] = None
          
          # حفظ النتيجة كملف JSON
          with open('data/certificates.json', 'w', encoding='utf-8') as f:
              json.dump(certificates, f, ensure_ascii=False, indent=2)
          EOF
          
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add data/certificates.json  # إضافة ملف JSON فقط (إزالة .xlsx إذا لم ترد تتبعه)
          git diff --quiet && git diff --staged --quiet || (git commit -m "تحديث تلقائي للبيانات من Excel" && git push)