name: Auto Sync Excel to JSON

on:
  push:
    paths:
      - 'data/certificates.xlsx'
  schedule:
    - cron: '*/30 * * * *'  # كل 30 دقيقة
  workflow_dispatch:  # للتشغيل اليدوي

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl
    
    - name: Convert Excel to JSON
      run: python convert.py
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
    
    - name: Commit and push if changed
      run: |
        git add data/certificates.json
        git diff --quiet && git diff --staged --quiet || (git commit -m "تحديث تلقائي للبيانات - $(date +'%Y-%m-%d %H:%M:%S')" && git push)
